# Permalinks
permalink:           pretty

# Setup
title:               Life
tagline:             'In Balance'
description:         'Letters at leisure, thoughts not at work. Made by <a href="https://twitter.com/tugglery" target="_blank">@tugglery</a>.'
url:                 http://rtuggle.github.io
baseurl:             '/life_blog'
paginate:            5

# About/contact
author:
  name:              Ryan Tuggle
  url:               https://twitter.com/tugglery
  email:             ryan.tuggle@gmail.com

# Custom vars
version:             1.0.0
